config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes, only: [:index, :new, :create, :show, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :update]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :Prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
  belongs_to :prototype
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base

  belongs_to :user
  belongs_to :prototype

end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :prototype_tags
  has_many :tags, through: :prototype_tag


  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end
end

app/models/prototype_tag.rb
class PrototypeTag < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :prototype_tags
  has_many :prototypes, through: :prototype_tag
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, UserImageUploader
  has_many :prototypes

  has_many :comments, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  def create
    @comment = Comment.create(comment_params)
    @group = Prototype.find(params[:prototype_id])
    respond_to do |format|
      format.html { redirect_to prototype_path(@group)  }
      format.json
    end
  end

  def edit
    respond_to do |format|
    format.html { redirect_to prototype_path(id: current_user.id)  }
    format.json
    end
  end

  def update
    @group = Prototype.find(params[:prototype_id])
    @comment.update(comment_params) if @comment.user_id == current_user.id
    respond_to do |format|
    format.html { redirect_to prototype_path(@group)  }
    format.json
    end
  end

  # def destroy
  #   @prototype = Prototype.find(params[:prototype_id])
  #   if @comment.user.id == current_user.id
  #     @comment.destroy
  #   end
  #   if @comment.destroy
  #     respond_to do |format|
  #     format.html { redirect_to prototype_path(@prototype)  }
  #     format.json { head :no_content }
  #     end
  #   else
  #     format.json
  #   end
  # end

  def destroy
    @prototype = Prototype.find(params[:prototype_id])
    if @comment.user.id == current_user.id
      @comment.destroy
      respond_to do |format|
      format.html { redirect_to prototype_path(@prototype)  }
      format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.json
      end
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.permit(:content).merge(prototype_id: params[:prototype_id], user_id: current_user.id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
    @like = Like.new(user_id: current_user.id, prototype_id: params[:prototype_id])
    if @like.save
      respond_to do |format|
        format.json
        format.html
      end
    end
  end

  def destroy
    Like.find(params[:id]).destroy
    respond_to do |format|
      format.json { head :no_content }
      format.html
    end
  end
# { @likes_number = Likes.where(group_id: params[:prototype_id]).count }

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: :show

  def index
    @prototypes = Prototype.order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to :new_prototype, alert: 'YNew prototype was unsuccessfully created'
     end
  end

  def show
    @like = Like.find_by("user_id = ? and prototype_id = ?", current_user.id, params[:id])
    if @like.present?
      @like_id = @like.id
      @like = true
    else
      @like = false
    end
    @likes_number = Like.where(prototype_id: params[:id]).count
    @comments = Comment.where("prototype_id = ?", params[:id]).order('created_at Asc')
    @comment = Comment.new
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    @prototype.destroy if @prototype.user_id == current_user.id
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace

    %link{rel: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", type: "stylesheet"}/

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    = csrf_meta_tags
    %link{:href => "https://use.fontawesome.com/releases/v5.0.6/css/all.css", :rel => "stylesheet"}/
  %body

    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/layouts/test.html.erb
<div class='media'>
  <div class='media-left'>
    <a href='/users/${comment.user_id}' title='thumbnail'>
      <img class="media-object" src="/uploads/noimage.png" alt="Noimage" width="64" height="64"/>
    </a>
  </div>
  <div class='media-body'>
    <h4>
      ${comment.name}
    </h4>
    <p>
      ${comment.content}
    </p>
    <div class='list-ui' style='list-style:none'>
      <a rel="nofollow" data-method="delete" href="/prototypes/18/comments/${comment.id}" method = "delete">
        <i class='fa fa-trash color'></i>
      </a>
    </div>
    <div class='list-ui' style='list-style:none'>
      <a href="/prototypes/18/comments/${comment.id}/edit" method= "patch">
        <i class='fa fa-edit color'></i>
      </a>
    </div>
  </div>
</div>

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-control
        - if user_signed_in? && current_user.id == prototype.user_id
          %i.fas.fa-edit
          = link_to "/prototypes/#{prototype.id}", method: :delete, data: {confirm: :'本当に削除しますか？'} do
            %i.fas.fa-trash-alt
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/destroy.html.haml
.contents_delete
  .success
    %h3
      削除が完了しました。
    %a{:href => "/"} 投稿一覧へ戻る

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload.image-upload--main
            = f.fields_for :captured_images do |image|
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"

        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "#"
        %li.btn-default.btn-popular
          = link_to "Newest", "#"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    %li.disabled
    = paginate @prototypes, theme: 'my_custom_theme'

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload.image-upload--main
            = f.fields_for :captured_images do |image|
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"

        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    -# %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav

    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
    .col-md-6.clearfix
      .likes-box
        %button#like-button.btn.btn-default.decrement-button
          - if @like == true
            %i.fa.fa-heart.like-clicked{"aria-hidden" => "true", data: { likeid: @like_id }}
          - else @like == false
            %i.fa.fa-heart{"aria-hidden" => "true"}
          = "&emsp;".html_safe + "like"
          %span#like-sum.num= @likes_number
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe
  #comment_list
    - if @comments
      - @comments.each do |text|
        .media
          .media-left
            %a(href="#{user_path(text.user.id)}" title="thumbnail")
              = image_tag "#{text.user.avatar}", size: '64x64', class: "media-object"
          .media-body
            %h4
              = text.user.name
            %p
              = text.content
            .list-ui{style: "list-style:none;"}
              = link_to "/prototypes/#{@prototype.id}/comments/#{text.id}" , method: :delete, remote: true do
                %i.fa.fa-trash.color
            .list-ui{style: "list-style:none;"}
              = link_to   do
                %i.fa.fa-edit.color{ data: {url: "/prototypes/#{@prototype.id}/comments/#{text.id}" }}
  #modal-main
    .destroy
      %i.fa.fa-times{"aria-hidden" => "true"}
    = form_tag (prototypes_path) , method: :patch do
      %p#modal-main__group-name
      %p 新しいコメントを入力してください
      = text_field_tag :content
      = submit_tag "送信"

  .form#new_comment.form_inline
    - if user_signed_in?
      %h4
        Write a comment
      .row
        = form_for [@prototype, @comment] do |f|
          .form-group.col-md-10
            = f.text_area :content, placeholder: 'Your comments', id: "comment_text", class: "textform-control"
          .form-group.col-md-2
            = f.submit "COMMENT"

app/views/prototypes/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes